# relative path to the directory containing texture and model resources
resourcesRoot: ./resources/

random:
  # The value of the random seed for the application
  seed: -1 # A value of -1 will result in a seed derived from the system clock value

input:
  # Enable keyboard and mouse input (via the application window)
  manual: true # It is advised to set one of manual XOR stdin to true
  # Enable input via stdin (each line will cause a new frame to render)
  stdin: false # Note: Enabling stdin will case render loop to block after each frame for input and will disable delta time

output:
  window:
    visible: true
    fullscreen: true
    width: 800
    height: 600
  # Output the frames of the application to the /frames directory
  frameImages: false
  # Output a colour image
  colour: true
  # Output a depth image
  depth: false # If outputting to window the depth output will be displayed instead of colour if this is true, if rendering to images, both can be output
  # Invert the depth colours (default: near = black, far = white)
  invertDepth: true

camera:
  startPosition: [ 0.0, 3.3, 0.0 ]
  # Enable/disable vertical motion
  verticalMovement: true

terrain:
  # The size of the scene to generate
  width: 100.0
  # The vertical scaling on the terrain geometry (larger value = taller terrain)
  verticalScale: 3.0
  noise:
    xScale: 1.0
    yScale: 1.0
    # The number of octaves of perlin noise (detail) to use (higher = more detail)
    octaves: 8
    # The amplitude multiplier for successive octaves (smaller = smoother terrain)
    persistence: 0.5
    # The frequency multiplier for successive octaves (>1 => each octave will contribute finer details)
    lacunarity: 2.0
  # Density of vertices in the terrain mesh (higher = more vertices)
  vertexDensity: 0.7
  texture:
    diffuse: "/textures/floor2.png/"
    normal: null

quadtree:
  # Levels of detail (LODs) in the quad-tree
  levels: 2
  # Distance multiplier for switching (LOD) (smaller = LOD threshold is closer)
  thresholdCoefficient: 1.7
  # Enable view-frustum culling of geometry
  frustumCulling: true

sceneObjects:
  display: true
  # List of tree types and their generation parameters
  trees:
    - !TreeTypes$BranchingTree
      name: tree 1
      lSystemParams:
        a: 0.3308
        lr: 1.109
        vr: 1.832
        e: 0.052
      branchings:
        - angles: [ 3.14159 ]
          prob: 0.3
        - angles: [ 1.6535, 2.3148 ]
          prob: 0.7
      # The fraction of all models of this tree which are instanced from a given generated mesh (random configuration) (Larger = more repeated instances)
      instanceFraction: 0.2
      # Size scalar for the models
      scale: 0.01
      # Size scalar for the leaf models
      leafXScale: 0.7
      leafYScale: 0.7
      barkTexture:
        diffuse: "/textures/Bark_02_2K_Base_Color.png"
        normal: "/textures/Bark_02_2K_Normal.png"
      leafTextures:
        frontAlbedo: "/textures/Leaf1/Leaf1_front.tga"
        frontNormal: "/textures/Leaf1/Leaf1_normals_front.tga"
        frontTranslucency: "/textures/Leaf1/Leaf1_front_t.tga"
        frontHalfLife: "/textures/Leaf1/Leaf1_halflife_front_t.tga"
        backAlbedo: "/textures/Leaf1/Leaf1_back.tga"
        backNormal: "/textures/Leaf1/Leaf1_normals_back.tga"
        backTranslucency: "/textures/Leaf1/Leaf1_back_t.tga"
        backHalfLife: "/textures/Leaf1/Leaf1_halflife_back_t.tga"
      # Number of sides to use in the cross section of the branches
      numSides: 6
      # Minimum number of iterations of the L-system
      minIterations: 7 # inclusive
      # Maximum number of iterations of the L-system
      maxIterations: 9 # exclusive
      # Density of models in the scene
      density: 0.8

    - !TreeTypes$MonopodialTree
      name: Monopodial Tree
      lSystemParams:
        lB: 2.0   # Base length
        lS: 1.1   # Side branch length
        lSm: 0.5  # Min ratio for side branch length (of ls) and width (of ws)
        wB: 0.5   # Base width
        wS: 0.3   # Side branch width
        wS2: 0.4  # 3rd level side branch width
        vr: 0.3   # Width of start of side branch
        aB: 80.0  # Branch angle to trunk
        aS: 110.0  # Branch angle around trunk
        aS2: 100.0 # 3rd level side branch angle
        aS3: 80.0  # 3rd level side branch angle downwards
        aS4: -45.0 # 3rd level side branch angle upwards for 2nd part
        aS5: 0.0   # Initial angle of rotation around branch for 3rd level side branches
        lS2: 0.333 # Distance ratio for gap between 3rd level branches (ignored for pine style branches)
        lS3: 0.25  # Distance ratio for first part of 3rd level branches (ignored for pine style branches)
        lS4: 0.25  # Distance ratio for second part of 3rd level branches (ignored for pine style branches)
        tH: 0.9    # Threshold for switching expansion/contraction (1 = bottom, 0 = top)
        aU: 0.0    # Angle to curve the side branches upwards
        nB: 8      # Number of side branches (and trunk height segments) per iteration
        nB2: 12    # Branching factor of side branches (ignored for pine style branches)
        l1: 0.2    # Length of trunk sections between branches
        l2: 0.0    # Length of trunk sections after branches
        lr: 0.5    # Offset of side branches from centre
        lr2: 1.0   # Ratio of decrease of l2
        e: 0.0     # Elasticity
      # The fraction of all models of this tree which are instanced from a given generated mesh (random configuration) (Larger = more repeated instances)
      instanceFraction: 0.2
      # Size scalar for the models
      scale: 0.75
      # Size scalar for the leaf models
      leafXScale: 0.17
      leafYScale: 0.17
      barkTexture:
        diffuse: "/textures/Bark_02_2K_Base_Color.png"
        normal: "/textures/Bark_02_2K_Normal.png"
      leafTextures:
        frontAlbedo: "/textures/Leaf3/Leaf3_front.tga"
        frontNormal: "/textures/Leaf3/Leaf3_normals_front.tga"
        frontTranslucency: "/textures/Leaf3/Leaf3_front_t.tga"
        frontHalfLife: "/textures/Leaf3/Leaf3_halflife_front_t.tga"
        backAlbedo: "/textures/Leaf3/Leaf3_back.tga"
        backNormal: "/textures/Leaf3/Leaf3_normals_back.tga"
        backTranslucency: "/textures/Leaf3/Leaf3_back_t.tga"
        backHalfLife: "/textures/Leaf3/Leaf3_halflife_back_t.tga"
      # Number of sides to use in the cross section of the branches
      numSides: 6
      # Minimum number of iterations of the L-system
      minIterations: 7 # inclusive
      # Maximum number of iterations of the L-system
      maxIterations: 9 # exclusive
      # Density of models in the scene
      density: 0.7
      # Vary branch angle with height (higher branches point upwards, flattening around tH then pointing down)
      heightVaryingAngles: true
      # Use pine tree style branching (opposite and recursive)
      pineStyleBranches: false

    - !TreeTypes$AspenTree
      name: Aspen
      lSystemParams:
        lB: 4.0   # Base length
        lS: 0.6   # Side branch length
        lSm: 0.4  # Min ratio for side branch length (of ls) and width (of ws)
        wB: 0.5   # Base width
        wS: 0.4  # Side branch width
        wS2: 0.4  # 3rd level side branch width
        vr: 0.04  # Width of start of side branch
        aB: 90.0  # Branch angle to trunk
        aS: 80.0  # Branch angle around trunk
        aS2: 140.0 # 3rd level side branch angle
        aS3: 60.0 # 3rd level side branch angle upwards
        aS4: 45.0 # 3rd level side branch angle upwards for 2nd part
        aS5: 0.0   # Initial angle of rotation around branch for 3rd level side branches
        lS2: 0.333 # Distance ratio for gap between 3rd level branches (ignored for pine style branches)
        lS3: 0.333  # Distance ratio for first part of 3rd level branches (ignored for pine style branches)
        lS4: 0.25  # Distance ratio for second part of 3rd level branches (ignored for pine style branches)
        tH: 0.7   # Threshold for switching expansion/contraction (1 = bottom, 0 = top)
        aU: 1.0  # Angle to curve the side branches upwards
        nB: 8     # Number of side branches (and trunk height segments) per iteration
        nB2: 17   # Branching factor of side branches (ignored for pine style branches)
        l1: 0.1   # Length of trunk sections between branches
        l2: 0.0   # Length of trunk sections after branches
        lr: 0.5   # Offset of side branches from centre
        lr2: 1.0  # Ratio of decrease of l2
        e: 0.0    # Elasticity
      # The fraction of all models of this tree which are instanced from a given generated mesh (random configuration) (Larger = more repeated instances)
      instanceFraction: 0.2
      # Size scalar for the models
      scale: 1.0
      # Size scalar for the leaf models
      leafXScale: 0.28
      leafYScale: 0.28
      barkTexture:
        diffuse: "/textures/Aspen_bark_001_COLOR.jpg"
        normal: "/textures/Aspen_bark_001_NORM.jpg"
      leafTextures:
        frontAlbedo: "/textures/Leaf2/Leaf2_front.tga"
        frontNormal: "/textures/Leaf2/Leaf2_normals_front.tga"
        frontTranslucency: "/textures/Leaf2/Leaf2_front_t.tga"
        frontHalfLife: "/textures/Leaf2/Leaf2_halflife_front_t.tga"
        backAlbedo: "/textures/Leaf2/Leaf2_back.tga"
        backNormal: "/textures/Leaf2/Leaf2_normals_back.tga"
        backTranslucency: "/textures/Leaf2/Leaf2_back_t.tga"
        backHalfLife: "/textures/Leaf2/Leaf2_halflife_back_t.tga"
      leafColourFilter:
        colour: [ 1.0, 0.79, 0.1 ]
        mixFactor: 0.9
        expMix: true
      # Number of sides to use in the cross section of the branches
      numSides: 6
      # Minimum number of iterations of the L-system
      minIterations: 10 # inclusive
      # Maximum number of iterations of the L-system
      maxIterations: 12 # exclusive
      # Density of models in the scene
      density: 0.7
      # Vary branch angle with height (higher branches point upwards, flattening around tH then pointing down)
      heightVaryingAngles: true
      # Use pine tree style branching (opposite and recursive)
      pineStyleBranches: false

    - !TreeTypes$PoplarTree
      name: Lombardy Poplar
      lSystemParams:
        lB: 0.0   # Base length
        lS: 1.06  # Side branch length
        lSm: 1.0  # Min ratio for side branch length (of ls) and width (of ws)
        wB: 0.7   # Base width
        wS: 0.3   # Side branch width
        wS2: 0.2  # 3rd level side branch width
        vr: 0.2   # Width of start of side branch
        aB: 35.0  # Branch angle to trunk
        aS: 80.0  # Branch angle around trunk
        aS2: 140.0 # 3rd level side branch angle
        aS3: 30.0 # 3rd level side branch angle upwards
        aS4: -20.0 # 3rd level side branch angle upwards for 2nd part
        aS5: 0.0   # Initial angle of rotation around branch for 3rd level side branches
        lS2: 0.333 # Distance ratio for gap between 3rd level branches (ignored for pine style branches)
        lS3: 0.25  # Distance ratio for first part of 3rd level branches (ignored for pine style branches)
        lS4: 0.25  # Distance ratio for second part of 3rd level branches (ignored for pine style branches)
        tH: 1.0   # Threshold for switching expansion/contraction (1 = bottom, 0 = top)
        aU: 1.2  # Angle to curve the side branches upwards
        nB: 2     # Number of side branches (and trunk height segments) per iteration
        nB2: 25   # Branching factor of side branches (ignored for pine style branches)
        l1: 0.5   # Length of trunk sections between branches
        l2: 0.0   # Length of trunk sections after branches
        lr: 0.0   # Offset of side branches from centre
        lr2: 1.0   # Ratio of decrease of l2
        e: -0.01  # Elasticity
      # The fraction of all models of this tree which are instanced from a given generated mesh (random configuration) (Larger = more repeated instances)
      instanceFraction: 0.2
      # Size scalar for the models
      scale: 0.7
      # Size scalar for the leaf models
      leafXScale: 0.15
      leafYScale: 0.15
      barkTexture:
        diffuse: "/textures/Bark_06_BaseColor.jpg"
        normal: "/textures/Bark_06_Normal.jpg"
      leafTextures:
        frontAlbedo: "/textures/Leaf2/Leaf2_front.tga"
        frontNormal: "/textures/Leaf2/Leaf2_normals_front.tga"
        frontTranslucency: "/textures/Leaf2/Leaf2_front_t.tga"
        frontHalfLife: "/textures/Leaf2/Leaf2_halflife_front_t.tga"
        backAlbedo: "/textures/Leaf2/Leaf2_back.tga"
        backNormal: "/textures/Leaf2/Leaf2_normals_back.tga"
        backTranslucency: "/textures/Leaf2/Leaf2_back_t.tga"
        backHalfLife: "/textures/Leaf2/Leaf2_halflife_back_t.tga"
      leafColourFilter:
        colour: [ 0.055, 0.21, 0.055 ]
        mixFactor: 0.7
        expMix: false
      # Number of sides to use in the cross section of the branches
      numSides: 6
      # Minimum number of iterations of the L-system
      minIterations: 13 # inclusive
      # Maximum number of iterations of the L-system
      maxIterations: 15 # exclusive
      # Density of models in the scene
      density: 0.7
      # Vary branch angle with height (higher branches point upwards, flattening around tH then pointing down)
      heightVaryingAngles: false
      # Use pine tree style branching (opposite and recursive)
      pineStyleBranches: false

    - !TreeTypes$PineTree
      name: Pine Tree
      lSystemParams:
        lB: 1.2   # Base length
        lS: 0.6   # Side branch length
        lSm: 0.025  # Min ratio for side branch length (of ls) and width (of ws)
        wB: 0.2   # Base width
        wS: 0.3   # Side branch width
        wS2: 0.8  # 3rd level side branch width
        vr: 0.25   # Width of start of side branch
        aB: 90.0  # Branch angle to trunk
        aS: 60.0  # Branch angle around trunk
        aS2: 0.0 # 3rd level side branch angle
        aS3: -45.0  # 3rd level side branch angle downwards
        aS4: 45.0 # 3rd level side branch angle upwards for 2nd part
        aS5: 0.0   # Initial angle of rotation around branch for 3rd level side branches
        lS2: 1.0 # Distance ratio for gap between 3rd level branches (ignored for pine style branches)
        lS3: 1.0  # Distance ratio for first part of 3rd level branches (ignored for pine style branches)
        lS4: 1.0  # Distance ratio for second part of 3rd level branches (ignored for pine style branches)
        tH: 1.0    # Threshold for switching expansion/contraction (1 = bottom, 0 = top)
        aU: 2.5    # Angle to curve the side branches upwards
        nB: 6      # Number of side branches (and trunk height segments) per iteration
        nB2: 1    # Branching factor of side branches (ignored for pine style branches)
        l1: 0.0    # Length of trunk sections between branches
        l2: 0.5    # Length of trunk sections after branches
        lr: 0.5    # Offset of side branches from centre
        lr2: 0.95   # Ratio of decrease of l2
        e: 0.0     # Elasticity
      # The fraction of all models of this tree which are instanced from a given generated mesh (random configuration) (Larger = more repeated instances)
      instanceFraction: 0.2
      # Size scalar for the models
      scale: 1.5
      # Size scalar for the leaf models
      leafXScale: 0.03
      leafYScale: 0.4
      barkTexture:
        diffuse: "/textures/Bark_02_2K_Base_Color.png"
        normal: "/textures/Bark_02_2K_Normal.png"
      leafTextures:
        frontAlbedo: "/textures/Leaf3/Leaf3_front.tga"
        frontNormal: "/textures/Leaf3/Leaf3_normals_front.tga"
        frontTranslucency: "/textures/Leaf3/Leaf3_front_t.tga"
        frontHalfLife: "/textures/Leaf3/Leaf3_halflife_front_t.tga"
        backAlbedo: "/textures/Leaf3/Leaf3_back.tga"
        backNormal: "/textures/Leaf3/Leaf3_normals_back.tga"
        backTranslucency: "/textures/Leaf3/Leaf3_back_t.tga"
        backHalfLife: "/textures/Leaf3/Leaf3_halflife_back_t.tga"
      # Number of sides to use in the cross section of the branches
      numSides: 6
      # Minimum number of iterations of the L-system
      minIterations: 8 # inclusive
      # Maximum number of iterations of the L-system
      maxIterations: 16 # exclusive
      # Density of models in the scene
      density: 0.7
      # Vary branch angle with height (higher branches point upwards, flattening around tH then pointing down)
      heightVaryingAngles: true
      # Use pine tree style branching (opposite and recursive)
      pineStyleBranches: true

  twigs:
    typesPerQuad: 2
    texture:
      diffuse: "/textures/Bark_Pine_baseColor.jpg"
      normal: "/textures/Bark_Pine_normal.jpg"
    numSides: 5
    # Density of models in the scene (to disable set to 0)
    density: 1.0
  externalModels:
    # Path to model (.obj) file
    - modelPath: "/models/Rock1/Rock1.obj"
      # Path to directory containing model textures defined in material file (.mtl)
      texturesDir: "/models/Rock1"
      # Texture to overwrite the model texture with (default = null)
      overwriteTexture:
        diffuse: null
        normal: null
      # Size scalar for the model
      scale: 0.3
      # Density of models in the scene
      density: 1.0
  crossedBillboards:
    # texture to use on the billboards
    - texture:
        diffuse: "/textures/grass2.png"
        normal: null
      # width scalar
      xScale: 1.0
      # height scalar
      yScale: 0.35
      # Density of models in the scene
      density: 20.0
      # texture to use on the billboards
    - texture:
        diffuse: "/textures/fern1_rotated.png"
        normal: null
      # width scalar
      xScale: 1.2
      # height scalar
      yScale: 1.2
      # Density of models in the scene
      density: 0.2
      # texture to use on the billboards
    - texture:
        diffuse: "/textures/fern2_rotated.png"
        normal: null
      # width scalar
      xScale: 1.2
      # height scalar
      yScale: 1.2
      # Density of models in the scene
      density: 0.2
  fallenLeaves:
    # Density of models in the scene (to disable set to 0)
    density: 1.0

lighting:
  # Strength of the ambient lighting in the scene
  ambientStrength: 0.2
  hdr:
    enabled: true
    # The exposure value to use in the tone mapping algorithm (larger = more light)
    exposure: 0.9
  gammaCorrection:
    enabled: true
    # The gamma value to use for gamma correction
    gamma: 2.2
  sun:
    # Display a polygon representation of the sun
    display: false
    # Number of sides to use in the polygon
    numSides: 10
    # Strength of sun to use in lighting calculations
    strength: 1.0
    # Position of the sun polygon and for use in lighting calculations (Currently overwritten by the HDR image)
    position: [ 50.0, 200.0, -50.0 ]
    # Scale of the sun polygon
    scale: 20.0
  ssao:
    enabled: true
    # Number of samples in the kernel
    kernelSize: 32
    # Radius of samples
    radius: 0.5
    # Bias for depth test
    bias: 0.025
  translucency:
    enabled: true
    # Scalar for leaf translucency (larger = brighter impact from translucency)
    factor: 0.5
  shadows:
    enabled: true
    # Resolution of the shadow map (larger scenes will need a larger resolution to avoid pixelation artefacts/missing details at the cost of GPU memory)
    resolution: 4096
  volumetricScattering:
    enabled: true
    # Number of samples along each light ray (larger = higher resolution)
    numSamples: 100
    # Density of samples along each light ray (smaller = samples taken from a smaller area = shorter, brighter rays)
    sampleDensity: 0.5
    # Impact decay of each sample (lower = greater fall-off)
    decay: 0.99 # range [0.0, 1.0)
    # Scalar for brightness of each ray (higher = brighter)
    exposure: 0.0015